---
apiVersion: v1
data:
  conig: |
    sso:
      issuer: https://login.microsoftonline.com/703922c4-f042-4683-9e67-a969c8abc975/v2.0
      redirectUrl: https://argo-workflows-yy.jumpingcrab.com/oauth2/callback
      clientId:
        name: argo-sso-secret
        key: oidc-azure-clientId
      clientSecret:
        name: argo-sso-secret
        key: oidc-azure-clientSecret
      scopes:
        - openid      
        - email
      customGroupClaimName: roles
      rbac:
        enabled: true
    artifactRepository:
        # -- Archive the main container logs as an artifact
        archiveLogs: true
        # @default -- See [values.yaml]
        azure: 
        endpoint: https://cdpargoaksyy.blob.core.windows.net
        container: argologs
        accountKeySecret:
            name: artifacts-secret
            key: storageaccount-access-key
kind: ConfigMap
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: workflow-controller
    app.kubernetes.io/instance: argo-workflows
    app.kubernetes.io/name: argo-workflows-cm
    app.kubernetes.io/part-of: argo-workflows
  name: argo-workflow-controller-configmap
  namespace: argo