# default sa for logged in user
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-default
  annotations:
    workflows.argoproj.io/rbac-rule: "true"
    workflows.argoproj.io/rbac-rule-precedence: "0"
secrets:
  - name: argo-sso-default-token
---
# admin sa for logged in user
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-admin
  annotations:
    workflows.argoproj.io/rbac-rule: {{ .Values.argo.argoSSOAdmin.rbacRule }}   #"'AppRole' in groups" # Has to be changed!!
    workflows.argoproj.io/rbac-rule-precedence: "100" # the highest precedence
secrets:
  - name: argo-sso-admin-token
---
# sa for workflow-controller
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-workflow
secrets:
  - name: argo-workflow-token
---
# k8s does not create token automatically
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-default-token
  annotations:
    kubernetes.io/service-account.name: argo-sso-default
---
# k8s does not create token automatically
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-admin-token
  annotations:
    kubernetes.io/service-account.name: argo-sso-admin
---
# k8s does not create token automatically
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-workflow-token
  annotations:
    kubernetes.io/service-account.name: argo-workflow
---
# ClusterRole for default sso account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-default-cluster-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - clusterworkflowtemplates
  - clusterworkflowtemplates/finalizers
  verbs:
  - get
  - list
  - watch
---
# ClusterRole for normal user
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  - secrets
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - workflows/finalizers
  - workflowtasksets
  - workflowtasksets/finalizers
  - workflowtemplates
  - workflowtemplates/finalizers
  - cronworkflows
  - cronworkflows/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - argoproj.io
  resources:
  - eventsources
  - sensors
  - workfloweventbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - get
  - delete
---
# Cluster role for the workflow executor
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-workflow-executor-role
# https://argoproj.github.io/argo-workflows/workflow-rbac/
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
# Role for Admins to access secrets in all namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-secrets-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-default-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-sso-default-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-sso-default
  namespace: {{ include "argo.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-admin
subjects:
- kind: ServiceAccount
  name: argo-sso-admin
  namespace: {{ include "argo.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-workflow-executor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow-executor-role
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: {{ include "argo.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-admin-secret-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-secrets-role
subjects:
- kind: ServiceAccount
  name: argo-sso-admin
  namespace: {{ include "argo.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ include "argo.namespace" . }}
  name: argo-sso-admin-argo-sso-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-sso-role
subjects:
- kind: ServiceAccount
  name: argo-sso-admin
  namespace: {{ include "argo.namespace" . }}
---