apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: argo-workflows
  name: argo-server-extra
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ''
    resources:
      - serviceaccounts
    verbs:
      - list
