apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  type: NodePort
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: grafana
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 472:472 /grafana"]
        volumeMounts:
        - name: grafana-home
          mountPath: /grafana
      containers:
      - image: grafana/grafana:5.4.3
        name: grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-home
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "false"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Admin
            #- name: GF_SERVER_ROOT_URL
            #value: /api/v1/proxy/namespaces/default/services/grafana/
      volumes:
      - name: grafana-home
        persistentVolumeClaim:
          claimName: grafana-vol
