kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-vol
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: prometheus-storage
