---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: | {{ .Values.rbac.policy.csv | trim | nindent 4 }}
  policy.default: {{ .Values.rbac.policy.default }}