---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 408e4354-59d7-4e35-967c-c5f9db52ff68
    azure.workload.identity/tenant-id: 703922c4-f042-4683-9e67-a969c8abc975
  name: sa-external-secrets
  namespace: argocd
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: argocd
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      authType: WorkloadIdentity
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://cdpargo-aks-yy-kv.vault.azure.net"
      serviceAccountRef:
        name: sa-external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: argocd
spec:
  refreshInterval: 1h           # rate ESO pulls Azure Key Vault
  secretStoreRef:
    kind: SecretStore
    name: azure-store           # name of the SecretStore (or kind specified)
  target:
    name: argocd-secret           # name of the k8s Secret to be created
    creationPolicy: Merge
  dataFrom:
  # find all secrets
  - find:
      name:
        regexp: ".*"
    rewrite:
    # replace all special symbols with _
    - regexp:
        source: "[^a-zA-Z0-9 -]"
        target: "_"

