---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.externalSecrets.WorkloadIdentity.clientId }}
    azure.workload.identity/tenant-id: {{ .Values.externalSecrets.WorkloadIdentity.tenantId }}
  name: {{ .Values.externalSecrets.serviceAccountName }}
  namespace: argo
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: argo
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      authType: WorkloadIdentity
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: {{ .Values.externalSecrets.secretStoreVaultUrl }}
      serviceAccountRef:
        name: {{ .Values.externalSecrets.serviceAccountName }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: argo
spec:
  refreshInterval: 1h           # rate ESO pulls Azure Key Vault
  secretStoreRef:
    kind: SecretStore
    name: azure-store           # name of the SecretStore (or kind specified)
  target:
    name: argo-sso-secret           # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  # find all secrets
  - find:
      name:
        regexp: ".*"
    rewrite:
    # replace all special symbols with _
    - regexp:
        source: "[^a-zA-Z0-9 -]"
        target: "_"
