---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certmanager.metadata.name }}
spec:
  acme:
    server: {{ .Values.certmanager.spec.acme.server }}
    email: {{ .Values.certmanager.spec.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.certmanager.spec.acme.privateKeySecretRef.name }}
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
