apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: argocd
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: {{ .Values.externalSecrets.serviceAccountName }}
  containers:
    - image: mcr.microsoft.com/azure-cli
      name: oidc
  nodeSelector:
    kubernetes.io/os: linux