---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 408e4354-59d7-4e35-967c-c5f9db52ff68
    azure.workload.identity/tenant-id: 703922c4-f042-4683-9e67-a969c8abc975
  name: sa-external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
