apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h           # rate ESO pulls Azure Key Vault
  secretStoreRef:
    kind: SecretStore
    name: azure-store           # name of the SecretStore (or kind specified)
  target:
    name: argocd-secret           # name of the k8s Secret to be created
    creationPolicy: Merge
  dataFrom:
  # find all secrets starting with dev-
  - find:
      name:
        regexp: ".*"
    rewrite:
    # replace all special symbols with _
    - regexp:
        source: "[^a-zA-Z0-9 -]"
        target: "_"
