apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: argocd-helm
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: argocd-helm
      valueFiles:
      - $values/{{ .Values.values }}    
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    ref: values 
  ignoreDifferences:
  - group: '*'
    kind: Secret
    name: argocd-secret
    namespace: argocd
    jsonPointers:
    - /data
    - /stringData
  - group: '*'
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd
    jsonPointers:
    - /data/host
    - /data/url
    - /stringData/host
    - /stringData/url