apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-events
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.argocd.project }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: argo-events
    targetRevision: {{ .Values.spec.source.targetRevision }}
    # helm:
    #   parameters:
    #   - name: installCRDs
    #     value: 'true'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true