---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      authType: WorkloadIdentity
      # URL of your vault instance, see: https://docs.microsoft.com/en-us/azure/key-vault/general/about-keys-secrets-certificates
      vaultUrl: "https://cdpargo-aks-yy-kv.vault.azure.net"
      serviceAccountRef:
        name: sa-external-secrets
