apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: argocd-config
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: argocd-config
      valueFiles:
      - $values/{{ .Values.values }}    
  - repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true      
  ignoreDifferences:
  - group: '*'
    kind: Secret
    name: argocd-secret
    namespace: argocd
    jsonPointers:
    - /data
    - /stringData
  - group: '*'
    kind: ConfigMap
    name: argocd-cm
    namespace: argocd
    jsonPointers:
    - /data/host
    - /data/url
    - /stringData/host
    - /stringData/url