apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-identity-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: azure-workload-identity-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://azure.github.io/azure-workload-identity/charts
    chart: workload-identity-webhook
    targetRevision: '1.1.0'
    helm:
      values: |
        azureTenantID: {{ .Values.tennantId }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true