apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.argocd.project }}
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: '1.11'
    helm:
      parameters:
      - name: installCRDs
        value: 'true'
  ignoreDifferences:
  # - group: '*'
  #   kind: Secret
  #   name: argocd-secret
  #   namespace: argocd
  #   jsonPointers:
  #   - /data
  #   - /stringData
  - group: 'admissionregistration.k8s.io'
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook