apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    version: 1.11
    helm:
      parameters:
        - installCRDs: true
      values:
        - issuer: letsencrypt
  # staging https://acme-staging-v02.api.letsencrypt.org/directory 
  # production https://acme-v02.api.letsencrypt.org/directory  
        - issuerUrl: https://acme-v02.api.letsencrypt.org/directory
        - email: yy@datainsights.de 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true