apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ include "argocd.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: {{ include "argocd.destination.server" . }}
  project: {{ include "argocd.projectname" . }}
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: '0.8.1'
    helm:
      parameters:
      - name: installCRDs
        value: 'true'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true




