apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ include "argocd.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: {{ include "argocd.destination.server" . }}
  project: {{ include "argocd.projectname" . }}
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: '4.6.0'
    helm:
      values: |
        controller:
          replicaCount: 2
          service:
            enabled: true
            annotations: {service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: healthz}      
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true


