apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-master
  namespace: monitoring
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
#      initContainers:
#      - name: init-sysctl
#        image: busybox:1.27.2
#        command:
#        - sysctl
#        - -w
#        - vm.max_map_count=262144
#        securityContext:
#          privileged: true
      containers:
      - name: es-master
        image: datasrs/docker-elasticsearch:6.1.4
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: CLUSTER_NAME
          value: myesdb
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_ENABLE
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          requests:
            memory: "1024Mi"
            cpu: 0.25
          limits:
            memory: "2048Mi"
            cpu: 1
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: prometheus-storage
  resources:
    requests:
      storage: 4Gi