{
 "title": "Kafka Connect",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_records_lag"
    }
   ]
  },
  {
   "title": "Kafka Connect Outgoing Byte Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_outgoing_byte_rate"
    }
   ]
  },
  {
   "title": "Kafka Connector Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_worker_metrics_connector_count"
    },
    {}
   ]
  },
  {
   "title": "Kafka Connect Heartbeat rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_coordinator_metrics_heartbeat_rate"
    }
   ]
  },
  {
   "title": "Kafka Connect IO Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_io_ratio"
    }
   ]
  },
  {
   "title": "Kafka Connector Running Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_running_ratio"
    }
   ]
  },
  {
   "title": "Connector Tasks Pause Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connector_task_metrics_pause_ratio"
    }
   ]
  },
  {
   "title": "Kafka Connect Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_connect_metrics_incoming_byte_rate"
    }
   ]
  },
  {
   "title": "Kafka Connect Metrics count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_kafka_metrics_count_count"
    },
    {}
   ]
  }
 ]
}