{
 "title": "Kafka Brokers Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(java_lang_operatingsystem_systemloadaverage{}[1m])"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(java_lang_garbagecollector_lastgcinfo_duration[5m]))"
    }
   ]
  },
  {
   "title": "Bytes out per topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_count{name=\"BytesOutPerSec\",topic!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Messages in per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\",topic!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(java_lang_memory_heapmemoryusage_used)"
    }
   ]
  },
  {
   "title": "Bytes in per topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_count{name=\"BytesInPerSec\",topic!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions per Topic",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "avg(kafka_cluster_partition_value{name=\"UnderReplicated\"}) by (topic)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions per topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_cluster_partition_value{name=\"UnderReplicated\",topic!=\"\"}[5m]))"
    }
   ]
  }
 ]
}