{
 "title": "Kubernetes Kafka resource metrics",
 "description": "Monitors Kafka metrics from Prometheus. Shows active controllers, partitions, ISR shrink rate, purgatory size etc. Uses JMX exporter.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": "label_values(kafka_log_logstartoffset, topic)"
   },
   {
    "name": "Broker",
    "label": "Kafka Broker",
    "query": "label_values(kafka_log_size, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Broker Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",kafka_broker_id=\"0\"}"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_cluster_partition_value{kafka_broker_id!=\"\", topic!=\"\",name=\"UnderReplicated\"})"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount{instance=~\"$Broker$\"}"
    }
   ]
  },
  {
   "title": "ISR shrink rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrshrinks_total{instance=~\"$Broker$\"}[5m]))"
    }
   ]
  },
  {
   "title": "ISR expansion rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(kafka_server_replicamanager_isrexpands_total{instance=~\"$Broker$\"}[5m]))"
    }
   ]
  },
  {
   "title": "Delayed Fetch operation purgatory size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_purgatorysize_delayedoperation_fetch{instance=~\"$Broker$\"}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$Topics Bytes In",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesin_total{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  {
   "title": "$Topics Bytes out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
   "format": "Bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_bytesout_total{instance=~\"$Broker$\", topic=~\"$Topics$\"})"
    }
   ]
  },
  { "title": "Network I/O pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Unclean leader election per sec",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (kafka_controller_controllerstats_uncleanleaderelectionspersec{instance=~\"$Broker$\"}[1m]))",
     "legendFormat": "Received"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Fetch requests in Purgatory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_delayedoperation_fetch{instance=~\"$Broker.*$\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Local request consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_localtimems_request_fetchconsumer_count{instance=~\"$Broker$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Remote request consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_remotetimems_request_fetchconsumer_count{instance=~\"$Broker$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request queue consumer fetch count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requestqueuetimems_request_fetchconsumer_count{instance=~\"$Broker$\"}[1m]))"
    }
   ]
  }
 ]
}