apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appprojects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # Application contains othre apps
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.argocd.project }}
  sources:
  - repoURL: {{ .Values.spec.source.repoURL }}
    path: argocd-appprojects
    targetRevision: {{ .Values.spec.source.targetRevision }}
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
