apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-tf
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: example
      filters:
        data:
          # Type of Github event that triggered the delivery: [pull_request, push, issues, label, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: headers.X-Github-Event
            type: string
            value:
              - push
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: app-name
                    - name: repo-url
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: app-name
                        - name: repo-url
                      artifacts:
                        - git:
                            repo: "{{inputs.parameters.repo-url}}"
                            singleBranch: true
                            branch: main
                            depth: 1
                          name: tfconfig
                          path: /tfconfig
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.repo-url}}"]
                    outputs:
                      artifacts:
                        - name: tfconfig
                          path: /tfconfig
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.repository.html_url
              dest: spec.arguments.parameters.1.value
      retryStrategy:
        steps: 3