apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-tf
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: example
      filters:
        data:
          # Type of Github event that triggered the delivery: [pull_request, push, issues, label, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: headers.X-Github-Event
            type: string
            value:
              - push
        exprs:
          - expr: modified =~ "apps-tf"
            fields:
              - name: modified
                path: body.commits.0.modified.0 #body.commits.#(modified.#(%"apps-tf*"))#.modified.0
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-              
              spec:
                entrypoint: main 
                arguments:
                  parameters:
                    - name: repo-url
                templates:
                  - name: git
                    inputs:
                      parameters:
                        - name: repo-url
                          value: "{{workflow.parameters.repo-url}}"
                      artifacts:
                        - git:
                            repo: "{{inputs.parameters.repo-url}}"
                            singleBranch: true
                            branch: main
                            depth: 1
                          name: tfconfig
                          path: /tfconfig
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.repo-url}}"]
                    outputs:
                      artifacts:
                        - name: tfconfig
                          path: /tfconfig
                  - name: tf-app
                    serviceAccountName: terraform-app-sa
                    metadata:
                      labels:
                        azure.workload.identity/use: "true"
                    volumes:
                      - emptyDir: {}
                        name: tfplan
                    inputs:
                      artifacts:
                        - name: tfconfig
                          path: /tfconfig                        
                    container:
                      image: cdpargoyy.azurecr.io/cdpargoyy/argo-app:52ea6a72aa5395c8db1b1d3e33c1e04a72afd259
                      name: tf-app
                      command: 
                        - sh
                        # - -c
                        - entrypoint.sh
                      args: [ 
                          # "sleep 6000"
                          "terraform plan -input=false \
                          -out=/tfplan/tfplan \
                          -var-file=/tfconfig/apps-tf/testapp/config.tfvars \
                          -var oidc_issuer_url='$(OIDC_ISSUER_URL)' \
                          -var virtual_network_subnet_ids='[$(VIRTUAL_NETWORK_SUBNET_IDS)]'"
                        ]
                      env:
                        - name: ARM_SUBSCRIPTION_ID
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: az_subscription_id
                        - name: RG_SA_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_rg
                        - name: SA_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_sa
                        - name: CONTAINER_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_container
                        - name: OIDC_ISSUER_URL
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: oidc_issuer_url
                        - name: VIRTUAL_NETWORK_SUBNET_IDS
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: virtual_network_subnet_ids
                        - name: APP_NAME
                          value: "testapp"
                      volumeMounts:
                        - mountPath: /tfplan
                          name: tfplan
                    outputs:
                      artifacts:
                        - name: tfplan
                          path: /tfplan/tfplan
                          archive:
                            none: {}
                  - name: main
                    dag:
                      tasks:
                        - name: git
                          template: git
                        - name: tf-plan
                          template: tf-app
                          arguments:
                            artifacts:
                              - name: tfconfig
                                from: "{{tasks.git.outputs.artifacts.tfconfig}}"
                          dependencies:
                            - git
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.repository.html_url
              dest: spec.arguments.parameters.0.value
      retryStrategy:
        steps: 3