apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-tf
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: example
      filters:
        data:
          # Type of Github event that triggered the delivery: [pull_request, push, issues, label, ...]
          # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
          - path: headers.X-Github-Event
            type: string
            value:
              - push
        exprs:
          - expr: modified =~ "apps-tf"
            fields:
              - name: modified
                path: body.commits.0.modified.0 #body.commits.#(modified.#(%"apps-tf*"))#.modified.0
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: github-              
              spec:
                entrypoint: main 
                arguments:
                  parameters:
                    - name: repo-url
                    - name: modified-configs
                templates:
                  - name: main
                    inputs:
                      parameters:
                        - name: modified-configs                  
                    dag:
                      tasks:
                        - name: git-app-repo
                          template: git
                        - name: tf
                          template: tf-dag
                          arguments:
                            parameters:
                              - name: modified-config
                                value: "{{item}}"
                              - name: jq-filter
                                value: ".app_name"
                            artifacts:
                              - name: tfconfig
                                from: "{{tasks.git-app-repo.outputs.artifacts.tfconfig}}"                                
                          withParam: "{{inputs.parameters.modified-configs}}"
                          dependencies:
                            - git-app-repo

                  - name: tf-dag
                    inputs:
                      parameters:
                        - name: modified-config
                      artifacts:
                        - name: tfconfig             
                    dag:
                      tasks:                   
                        - name: jq-app-name
                          template: jq
                          arguments:
                            parameters:
                              - name: config
                                value: "{{inputs.parameters.modified-config}}"
                              - name: jq-filter
                                value: ".app_name"
                            artifacts:
                              - name: tfconfig
                                from: "{{inputs.artifacts.tfconfig}}"                              
                        - name: jq-tf-version
                          template: jq
                          arguments:
                            parameters:
                              - name: config
                                value: "{{inputs.parameters.modified-config}}"
                              - name: jq-filter
                                value: ".tf_version"
                            artifacts:
                              - name: tfconfig
                                from: "{{inputs.artifacts.tfconfig}}"
                        - name: tf-plan
                          template: tf-plan
                          arguments:
                            parameters:
                              - name: app_name
                                value: "{{tasks.jq-app-name.outputs.result}}"
                              - name: config
                                value: "{{inputs.parameters.modified-config}}"                                
                              - name: tf_version
                                value: "{{tasks.jq-tf-version.outputs.result}}"
                            artifacts:
                              - name: tfconfig
                                from: "{{inputs.artifacts.tfconfig}}"
                          dependencies:
                            - jq-app-name
                            - jq-tf-version
                        - name: tf-apply
                          template: tf-apply
                          arguments:
                            parameters:
                              - name: app_name
                                value: "{{tasks.jq-app-name.outputs.result}}"                          
                            artifacts:
                              - name: tfplan
                                from: "{{tasks.tf-plan.outputs.artifacts.tfplan}}"
                          dependencies:
                            - tf-plan

                  - name: git
                    inputs:
                      parameters:
                        - name: repo-url
                          value: "{{workflow.parameters.repo-url}}"
                      artifacts:
                        - git:
                            repo: "{{inputs.parameters.repo-url}}"
                            singleBranch: true
                            branch: main
                            depth: 1
                          name: tfconfig
                          path: /tfconfig
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.repo-url}}"]
                    outputs:
                      artifacts:
                        - name: tfconfig
                          path: /tfconfig

                  - name: jq
                    inputs:
                      parameters:
                        - name: config
                        - name: jq-filter
                      artifacts:
                        - name: tfconfig
                          path: /tfconfig                     
                    container:
                      image: stedolan/jq:latest
                      command: ["/usr/local/bin/jq"]
                      args: [
                              "-r",
                              "{{inputs.parameters.jq-filter}}",
                              "/tfconfig/{{inputs.parameters.config}}"
                            ]
                  - name: tf-plan
                    serviceAccountName: terraform-app-sa
                    metadata:
                      labels:
                        azure.workload.identity/use: "true"
                    volumes:
                      - emptyDir: {}
                        name: tfplan
                    inputs:
                      parameters:
                        - name: app_name
                        - name: config
                        - name: tf_version
                      artifacts:
                        - name: tfconfig
                          path: /tfconfig                        
                    container:
                      image: cdpargoyy.azurecr.io/cdpargoyy/argo-app:{{inputs.parameters.tf_version}}
                      name: tf-app
                      args: [
                              "terraform",
                              "plan",
                              "-input=false",
                              "-out=/tfplan/tfplan",
                              "-var-file=/tfconfig/{{inputs.parameters.config}}",
                              "-var",
                              "oidc_issuer_url=\"$(OIDC_ISSUER_URL)\"",
                              "-var",
                              "virtual_network_subnet_ids=[$(VIRTUAL_NETWORK_SUBNET_IDS)]"
                            ]
                      env:
                        - name: ARM_SUBSCRIPTION_ID
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: az_subscription_id
                        - name: RG_SA_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_rg
                        - name: SA_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_sa
                        - name: CONTAINER_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_container
                        - name: OIDC_ISSUER_URL
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: oidc_issuer_url
                        - name: VIRTUAL_NETWORK_SUBNET_IDS
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: virtual_network_subnet_ids
                        - name: APP_NAME
                          value: "{{inputs.parameters.app_name}}"
                      volumeMounts:
                        - mountPath: /tfplan
                          name: tfplan
                    outputs:
                      artifacts:
                        - name: tfplan
                          path: /tfplan/tfplan
                          archive:
                            none: {}
                  - name: tf-apply
                    serviceAccountName: terraform-app-sa
                    metadata:
                      labels:
                        azure.workload.identity/use: "true"
                    inputs:
                      parameters:
                        - name: app_name
                        - name: tf_version
                      artifacts:
                        - name: tfplan
                          path: /tfplan/tfplan
                    container:
                      image: cdpargoyy.azurecr.io/cdpargoyy/argo-app:{{inputs.parameters.tf_version}}
                      name: tf-app
                      args: [
                              "terraform",
                              "apply",
                              "-input=false",
                              "/tfplan/tfplan",
                            ]
                      env:
                        - name: ARM_SUBSCRIPTION_ID
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: az_subscription_id
                        - name: RG_SA_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_rg
                        - name: SA_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_sa
                        - name: CONTAINER_STATE
                          valueFrom:
                            configMapKeyRef:
                              name: tf-configmap
                              key: state_container
                        - name: APP_NAME
                          value: "{{inputs.parameters.app_name}}"
                      volumeMounts:
                        - mountPath: /tfplan
                          name: tfplan
                  - name: wait
                    suspend: {}
                      
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.repository.html_url
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.commits.#(modified.#(%"apps-tf*"))#.modified.#(%"apps-tf*")#|@flatten   #.modified.#(%"apps-tf*")
              dest: spec.arguments.parameters.1.value              
      retryStrategy:
        steps: 3