---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-sso-admin-events-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-aggregate-to-admin
subjects:
- kind: ServiceAccount
  name: argo-sso-admin
  namespace: argo