apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: sample-app
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
  roles:
  - name: dev
    description: DevOps privileges on the namespace
    policies:
    - p, proj:sample-project:dev, applications, get, sample-app/*, allow
    - p, proj:sample-project:dev, applications, sync, sample-app/*, allow
    - p, proj:sample-project:dev, applications, delete, sample-app/*, allow
    - p, proj:sample-project:dev, applications, action/*, sample-app/*, allow
    - p, proj:sample-project:dev, logs, get, sample-app/*, allow
    - p, proj:sample-project:dev, exec, create, sample-app/*, allow
