certmanager:
  metadata:
    name: letsencrypt
  spec:
    acme:
      # staging https://acme-staging-v02.api.letsencrypt.org/directory 
      # production https://acme-v02.api.letsencrypt.org/directory  
      server: https://acme-v02.api.letsencrypt.org/directory
      email: yy@datainsights.de
      privateKeySecretRef:
        name: letsencrypt

argocd:
  domainname: argocd.crabdance.com

  oidc:
    # the names of clienId and clientSecret secrets in the key Vault
    clientID: argocd-sso-secret:oidc-azure-clientId
    clientSecret: argocd-sso-secret:oidc-azure-clientSecret
    requestedScopes:
        - openid
        - email

  rbac:
    policy:
      csv: |
        p, role:ops, applications, *, */*, allow
        p, role:ops, logs, get, */*, allow
        p, role:ops, exec, create, */*, allow
        p, role:ops, clusters, get, *, allow
        p, role:ops, repositories, get, *, allow
        g, Admin, role:admin
      default: role:readonly
    scopes: '[roles, email]'

tennantId: 703922c4-0000-0000-0000-a969c8abc975

externalSecrets:
  serviceAccountName: external-secrets-sa
  secretStoreVaultUrl: "https://cdpargo-aks-yy-kv.vault.azure.net" 
  WorkloadIdentity:
    clientId: 408e4354-0000-0000-0000-c5f9db52ff68
    tenantId: 703922c4-0000-0000-0000-a969c8abc975