apiVersion: v2
name: argo-workflows
description: A Helm chart for Argo Workflows

type: application
version: 0.1.0

dependencies:
- name: argo-workflows
  version: "0.26.5"
  repository: https://argoproj.github.io/argo-helm