argo-workflows:
  singleNamespace: false
  fullnameOverride: "argo"
  workflow:
    create: true
    serviceAccount:
      name: "argo-workflow"
    rbac:
      create: true
  controller:
    name: workflow-controller
    serviceAccount:
      # -- Create a service account for the controller
      create: true
      # -- Service account name
      name: "argo-controller"
      # -- Annotations applied to created service account
      annotations: {}
    workflowNamespaces:
      - argo
    rbac:
      create: true

    workflowDefaults:
      spec:
        # set default serviceAccount
        serviceAccountName: argo-workflow

    # -- The number of controller pods to run
    replicas: 1

  server:
    serviceAccount:
      create: true
      name: "argo-server"
    rbac:
      # -- Adds Role and RoleBinding for the server.
      create: true   
    replicas: 1
   
    extraEnv:
      - name: SSO_DELEGATE_RBAC_TO_NAMESPACE
        value: "true"
    extraArgs:
      - --auth-mode
      - sso
      - --auth-mode
      - client
    secure: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: https
      hosts: [] # from values
      ingressClassName: "nginx"
      tls: []
    logging:
      # -- Set the logging level (one of: `debug`, `info`, `warn`, `error`)
      level: info


