apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
  name: prometheus-storage
allowVolumeExpansion: true
parameters:
  protocol: nfs
  skuName: Standard_LRS
provisioner: blob.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: Immediate
