---
# bind the argo-events-aggregate role to argo-sso-admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-events-argo-sso-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-events-aggregate-to-admin
subjects:
- kind: ServiceAccount
  name: argo-sso-admin
  namespace: argo

---
# binding argo-workflow-executor-role to argo service account in argo-events to allow to run pods
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-05-16T16:44:02Z"
  name: argo-workflow
  namespace: argo-events
secrets:
  - name: argo-workflow-token
---
# k8s does not create token automatically
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: argo-events
  name: argo-workflow-token
  annotations:
    kubernetes.io/service-account.name: argo-workflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-executor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow-executor-role
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: argo-events