kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    templates:
    - '/etc/alertmanager/*.tmpl'
    route:
      receiver: slack_demo
      group_by: ['alertname', 'priority']
      group_wait: 10s
      repeat_interval: 30m
      routes:
        - receiver: slack_demo
        # Send severity=slack alerts to slack.
          match:
            severity: page
          group_wait: 10s
          repeat_interval: 1m
 
    receivers:
    #- name: alert-emailer
    #  email_configs:
    #  - to: socrates@datainsights.de
    #    send_resolved: false
    #    from: socrates@datainsights.de
    #    smarthost: smtp.eample.com:25
    #    require_tls: false
    - name: slack_demo
      slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: '#jenkinsbuilds'
 