# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# list of Resource Config to be Applied
resources:
  - monitoring/max-map-count-setter.yaml
  - monitoring/prometheus/clusterRole.yaml
  - monitoring/prometheus/config-map.yaml
  - monitoring/prometheus/prometheus-storage.yaml
  - monitoring/prometheus/prometheus-pvc.yaml
  - monitoring/prometheus/prometheus-deployment.yaml
  - monitoring/prometheus/prometheus-service.yaml
  - monitoring/grafana/grafana-pvc.yaml
  - monitoring/grafana/grafana.yml
  - logging/elasticsearch/es-discovery-svc.yaml
  - logging/elasticsearch/es-master.yaml
  - logging/elasticsearch/es-svc.yaml
  - logging/filebeat/filebeat-config.yml
  - logging/filebeat/filebeat-ds.yml
  - logging/kibana/kibana-svc.yaml
  - logging/kibana/kibana.yaml
  - logging/logstash/logstash-config.yaml
  - logging/logstash/logstash-deployment.yaml
  - logging/logstash/logstash-service.yaml
  - alerting/alertmanager/configmap.yaml
  - alerting/alertmanager/configmapAlertTemplate.yaml
  - alerting/alertmanager/deployment.yaml
#  - cicd/jenkins/jenkins.yaml

# labels added to all Resources
commonLabels:
  app.kubernetes.io/name: kafka-cluster

namespace: k8s-lookout