apiVersion: v1
data:
  oidc.config: |
    name: Azure
    issuer: https://login.microsoftonline.com/{{- .Values.tennantId -}}/v2.0
    {{ $clientID := .Values.oidc.clientID -}}
    clientID: {{ printf "$%s" $clientID }}
    {{ $clientSecret := .Values.oidc.clientSecret -}}    
    clientSecret: {{ printf "$%s" $clientSecret }}
    requestedScopes: {{ .Values.oidc.requestedScopes }}
  url: https://{{- .Values.argocd.domainname -}}/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  # namespace: argocd
