---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: default
  source:
    path: base
    repoURL: {{- .Values.argocd.repoURL -}}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: '*'
    kind: Secret
    name: argocd-secret
    jsonPointers:
    - /data
    - /stringData
  - group: '*'
    kind: ConfigMap
    name: argocd-cm
    jsonPointers:
    - /data/host
    - /data/url
    - /stringData/host
    - /stringData/url
