apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appprojects
  namespace: {{ include "argocd.namespace" .}}
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # Application contains othre apps
  destination:
    namespace: {{ include "argocd.namespace" .}}
    server: {{ include "argocd.destination.server" . }}
  project: {{ include "argocd.projectname" . }}
  sources:
  - repoURL: {{ .Values.argocd.spec.sources.applications.repoURL }}
    path: appprojects
    targetRevision: {{ .Values.argocd.spec.sources.applications.targetRevision }}
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
