apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 1
  name: {{ include "argocd.projectname" . }}
  namespace: {{ include "argocd.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}
