apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: argocd
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: terraform-app-sa
  containers:
    - image: cdpargoyy.azurecr.io/cdpargoyy/argo-app:3b03a7b610cb7ea18e454dac7b1ef589a75c0b5b
      name: oidc
      command:  
      - sleep  
      - "6000"        
  nodeSelector:
    kubernetes.io/os: linux